[package]
name = "purepreval"
version = "0.1.0"
edition = "2024"

[dependencies]
postcard = { version = "1.1.3", features = ["use-std"] }
serde = { version = "1.0.228", features = ["derive"] }
x86_64builder = { path = "x86_64builder" }
